### PR TITLE
Added UI update

### PR DESCRIPTION
**Pull request by mohittk**
image

### CODE REVIEW

**Comment by mohittk** [comment]
@svenpetermanec bro when will I be getting reply of this PR?

**Comment by mohittk** [comment]
hey! @svenpetermanec any reason for closing the PR? where is my mistake?

**Comment by svenpetermanec** [comment]
> hey! @svenpetermanec any reason for closing the PR? where is my mistake?

No mistakes, it's just that the project does not need an UI update.

**Comment by mohittk** [comment]
> > hey! @svenpetermanec any reason for closing the PR? where is my mistake?
> 
> No mistakes, it's just that the project does not need an UI update.

Okay!

**Pull request closed without merging**
